### ISSUE TITLE
12 Factor Apps 12factor.org/net/com

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-incubator-playbook#13]

**Comment by anchit-chandran** [comment]
do you want this in the license section as a link as per dGC, or it's own section?
![image](https://user-images.githubusercontent.com/68898006/229557262-f6044ae0-6ec0-4d75-8d4e-1647dd40d88b.png)

**Comment by pacharanero** [comment]
12Factor overview can go in its own page, under 'Principles' top level nav

**Comment by anchit-chandran** [comment]
filled as many examples but can't think of ones for the last few 

![Image](https://user-images.githubusercontent.com/68898006/230590523-bc262c00-16c9-4985-b0dd-877c7cbd3d6f.png)
