### ISSUE TITLE
add PDF download option (take config from dGC or e12, and Download page button as template)

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-incubator-playbook#21]

**Comment by anchit-chandran** [comment]
what else do i need to do? currently this button is giving 404 on click.

the redboxes are the only things I assumed I need to change 

![Image](https://user-images.githubusercontent.com/68898006/230613860-dc674b01-2f86-4f81-9897-2045770ee788.png)

**Comment by pacharanero** [comment]
Browser console will let you what path it's looking for and not finding

**Comment by anchit-chandran** [comment]
Realised it's just that I hadn't set the `ENABLE_PDF_EXPORT=1` env var. Closing as works now (just need to ensure we set that env var on build)
